# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Twitter-FriendFinder
version:      0.03
version_from: lib/Net/Twitter/FriendFinder.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    Net::Twitter::Diff:            0
    Test::More:                    0
    Text::SimpleTable:             0
    URI:                           0
    URI::Escape:                   0
    Web::Scraper:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
